name: CI
run-name: "CI run by @${{ github.actor }}, event: ${{ github.event_name }}"
on:
    pull_request:
        branches: [main]
    push:
        branches: [main]
    workflow_call:
    workflow_dispatch:
concurrency:
    group: ci ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true
jobs:
    functional-tests:
        permissions:
            contents: read
        secrets: inherit
        uses: ./.github/workflows/functional-tests.yml
    security-tests:
        permissions:
            contents: read
        secrets: inherit
        uses: ./.github/workflows/security-tests.yml