name: StaticCodeAnalysis
run-name: "Static Code Analysis run by @${{ github.actor }}, event: ${{ github.event_name }}"
on:
    workflow_call:
    workflow_dispatch:

jobs:
    linting:
        runs-on: ubuntu-latest
        permissions:
            contents: read
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Set up JDK
              uses: actions/setup-java@v4
              with:
                  java-version: '11'
                  distribution: 'temurin'
            - name: Linting
              run: mvn spotbugs:check
            - name: Generate report
              if: failure()
              run: mvn spotbugs:gui
            - uses: actions/upload-artifact@v4
              if: failure()
              with:
                  name: spotbugs-report
                  path: target/spotbugsXml.xml
            - name: Analyse Linting Results
              uses: jwgmeligmeyling/spotbugs-github-action@master
              with:
                path: '**/spotbugsXml.xml'